import java.util.Scanner;

public class WeirdAlgorithm {
    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        long n = sc.nextLong();
        sc.close();
        System.out.print(n+" ");
        while (n != 1) {
            if ((n&1) == 0) {
                n /= 2;
            } else {
                n = 3 * n + 1;
            }
            System.out.print(n+" ");
        }
    }
}

// This program implements the "Weird Algorithm" as described in the problem statement.
// It takes a number n as input and prints the sequence of numbers generated by the algorithm
// until it reaches 1. The algorithm works as follows:
// - If n is even, divide it by 2.
// - If n is odd, multiply it by 3 and add 1.
// The program continues this process until n becomes 1, at which point it stops.
// The output is the sequence of numbers generated by the algorithm, starting from n and ending with 1.
// The program uses a while loop to repeatedly apply the algorithm and print the current value of n.